// PrimitiveDataTypePractice primitiveOne =new PrimitiveDataTypePractice();
// primitiveOne.primitiveTest();

// PrimitiveDataTypeDemo time1 = new PrimitiveDataTypeDemo();

// time1.printNewDateTime();

// DateTimeMethodsDemo timeMonth = new DateTimeMethodsDemo();

// timeMonth.calculateAgeInMonths();

// timeDay.calculateAgeInDays();

DateTimeMethodsDemo endDate1 = new DateTimeMethodsDemo();
// endDate1.printSubscriptionEndDate();
endDate1.printOffeEndDateTime();
