public class Planets {
  //Create a class named as Planets. Each planet has a name, planet number in the solar system, and number of moons planet has. Declare the class variables accordingly.
  // In anonymous apex, create objects for Earth and your favorite non-earth planet and print the object values in debug message

  public static String name;
  public static integer planetNumber;
  public static integer numberOfMoons;
}
