public class ShowStudentInformation {
    
    // - We will create another class called ShowStudentInformation 
    // - which will have the method named as showStudentInfo which will have the list of StudentInformation as parameter to show the student information. 

    public static void showStudentInfo(List<StudentInformation> studentInfo){
     System.debug(studentInfo);
        
    }
    // - From anonymous window you will pass the list of StudentInformation and information of all students should be printed.





}